// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But we want to create a sidebar manually
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'index',
      label: 'Table of Contents',
    },
    {
      type: 'category',
      label: 'Chapter 1: Foundations of Physical AI',
      items: [
        'chapter-1/introduction',
        'chapter-1/history-and-evolution',
        'chapter-1/core-concepts',
      ],
    },
    {
      type: 'category',
      label: 'Chapter 2: Humanoid Robot Design and Kinematics',
      items: [
        'chapter-2/mechanical-design-and-materials',
        'chapter-2/kinematics-and-dynamics',
        'chapter-2/actuators-and-sensors',
      ],
    },
    {
      type: 'category',
      label: 'Chapter 3: Perception and World Modeling',
      items: [
        'chapter-3/sensor-fusion',
        'chapter-3/computer-vision-for-robotics',
        'chapter-3/semantic-world-modeling',
      ],
    },
    {
      type: 'category',
      label: 'Chapter 4: Planning, Control, and Learning',
      items: [
        'chapter-4/motion-planning-algorithms',
        'chapter-4/advanced-control-systems',
        'chapter-4/reinforcement-learning-and-sim-to-real',
      ],
    },
    {
      type: 'category',
      label: 'Chapter 5: System Integration, Testing, and Future Directions',
      items: [
        'chapter-5/system-integration-and-ros',
        'chapter-5/testing-and-validation',
        'chapter-5/the-future-of-humanoid-robotics',
      ],
    },
  ],
};

module.exports = sidebars;
